from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]

NAV = """<header class='sticky top-0 z-50 border-b border-border bg-white/95 backdrop-blur'>
  <nav class='container-xl flex min-h-16 items-center justify-between gap-5' aria-label='Primary navigation'>
    <a href='/' class='flex items-center gap-3'><span class='grid h-10 w-10 place-items-center rounded-full bg-primary text-sm font-black text-white shadow-soft'>HU</span><span class='font-heading text-lg font-semibold'>Top Huatulco</span></a>
    <div class='hidden items-center gap-5 text-sm font-bold text-ink/75 xl:flex'><a href='/destinations/' class='hover:text-primary'>Bays</a><a href='/beaches/' class='hover:text-primary'>Beaches</a><a href='/towns-cities/' class='hover:text-primary'>Towns</a><a href='/things-to-do/' class='hover:text-primary'>Things to do</a><a href='/itineraries/' class='hover:text-primary'>Itineraries</a><a href='/travel-guide/' class='hover:text-primary'>Travel guide</a><a href='/food-culture/' class='hover:text-primary'>Food</a><a href='/tours/' class='hover:text-primary'>Tours</a></div>
    <button type='button' class='inline-flex h-11 w-11 items-center justify-center rounded-full border border-border bg-white text-ink shadow-soft xl:hidden' data-mobile-menu-button aria-controls='mobile-menu' aria-expanded='false' aria-label='Open navigation menu'><svg class='site-icon' data-menu-icon aria-hidden='true'><use href='/icons.svg#bars'></use></svg></button>
  </nav>
  <div id='mobile-menu' data-mobile-menu class='container-xl hidden pb-4 xl:hidden'><div class='rounded-[1.5rem] border border-border bg-white p-3 text-sm font-bold shadow-card'><a href='/destinations/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Bays</a><a href='/beaches/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Beaches</a><a href='/towns-cities/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Towns</a><a href='/things-to-do/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Things to do</a><a href='/itineraries/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Itineraries</a><a href='/travel-guide/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Travel guide</a><a href='/food-culture/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Food</a><a href='/tours/' class='block rounded-2xl px-4 py-3 hover:bg-secondary'>Tours</a></div></div>
</header>"""

FOOTER = """<footer class='border-t border-border bg-surface py-10 text-sm text-ink/60'><div class='container-xl grid gap-4 md:grid-cols-2'><div><strong class='text-ink'>Top Huatulco</strong><p class='mt-2'>Practical travel guides for Huatulco and the Oaxaca coast.</p></div><div class='md:text-right'><a href='/about/' class='font-bold text-primary'>About</a><span class='mx-2'>•</span><a href='/image-credits/' class='font-bold text-primary'>Sources & credits</a><span class='mx-2'>•</span><a href='/privacy/' class='font-bold text-primary'>Privacy</a></div></div></footer>"""

def page(title, desc, route, kicker, h1, intro, body, extra_head=""):
    return f"""<!doctype html>
<html lang='en'>
<head>
  <meta charset='UTF-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title>{title}</title>
  <meta name='description' content='{desc}'>
  <link rel='canonical' href='https://tophuatulco.com{route}'>
  <meta property='og:type' content='article'>
  <meta property='og:title' content='{title}'>
  <meta property='og:description' content='{desc}'>
  <meta property='og:url' content='https://tophuatulco.com{route}'>
  <meta name='theme-color' content='#2C9AB7'>
  {extra_head}
</head>
<body class='bg-background text-ink'>
{NAV}
<main data-priority-guide-depth='visitor-reference'>
<section class='bg-[linear-gradient(135deg,#EBF8FA_0%,#FFF7ED_100%)] py-12 sm:py-16'>
  <div class='container-xl'>
    <p class='font-script text-2xl leading-none text-primary'>{kicker}</p>
    <h1 class='mt-3 max-w-4xl text-4xl font-semibold tracking-tight sm:text-5xl'>{h1}</h1>
    <p class='mt-4 max-w-3xl text-base leading-8 text-ink/70 sm:text-lg'>{intro}</p>
  </div>
</section>
{body}
</main>
{FOOTER}
<script type='module' src='/src/main.js'></script>
</body></html>"""

def card(title, text):
    return f"<div class='card flex h-full flex-col p-6'><h3 class='font-heading text-xl font-semibold text-ink'>{title}</h3><p class='mt-3 leading-7 text-ink/75'>{text}</p></div>"

def source_box(items):
    lis = ''.join(f"<li><a class='font-bold text-primary hover:underline' href='{url}'>{label}</a> — {note}</li>" for label, url, note in items)
    return f"<section class='section-pad bg-surface' data-visible-sources='true'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>Check current details before you go</h2><p class='mt-3 leading-7 text-ink/75'>Use this page for decision-making, then confirm live transport, access, events, menus, and weather the week you travel.</p><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'>{lis}</ul></div></div></section>"

def write(rel, html):
    path = ROOT / rel.strip('/') / 'index.html' if rel != '/' else ROOT / 'index.html'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding='utf-8')

TOWN_DATA = {
'/towns-cities/la-crucecita/': dict(title='La Crucecita Visitor Guide | Top Huatulco', h1='La Crucecita', intro='Use La Crucecita as Huatulco’s practical town center: dinners, markets, pharmacies, banks, mezcal, coffee, errands, and an easy evening away from the resort strip.', verdict='Best for: dinner, errands, zócalo evenings, churches, market browsing, and a low-friction first night. Avoid as your only beach base: it is inland, so you still need taxis or local transport to swim.', plan='Start around the zócalo and Iglesia de La Crucecita, then work outward to Mercado 3 de Mayo, Calle Gardenia, cafés, mezcalerías, and restaurants such as Terra-Cotta or El Sabor de Oaxaca. Go late afternoon if you want errands plus dinner; go morning if markets and practical shopping matter most.', pair='Pair it with Chahué for a relaxed swim, Santa Cruz if you are coming from a boat tour, or a market-focused lunch before returning to Tangolunda. It is the easiest town to use when weather interrupts a beach day.'),
'/towns-cities/santa-cruz/': dict(title='Santa Cruz Huatulco Guide | Top Huatulco', h1='Santa Cruz', intro='Santa Cruz is the marina/cruise-facing bay: useful for boat departures, first swims, casual seafood, souvenir browsing, and logistics around the waterfront.', verdict='Best for: boat-tour starts, easy family swimming, cruise-day services, beachfront meals, and quick orientation. Avoid if you want the quietest sand or the most local evening scene.', plan='Use the waterfront as a staging point: confirm your boat meeting spot, check sea conditions, eat early if you are doing a morning bay tour, and leave time for parking or taxi drop-off near the pier. If no boat is planned, treat Santa Cruz as an easy half-day rather than the whole trip.', pair='Pair with La Crucecita for dinner, Chahué for a calmer afternoon, or a nine-bay boat route that continues toward Maguey, Cacaluta, Chachacual, or San Agustín depending on conditions.'),
'/towns-cities/copalita/': dict(title='Copalita Area Guide | Top Huatulco', h1='Copalita', intro='Copalita is the western edge of the Huatulco visitor map: river mouth, surf-facing coastline, Bocana beach energy, and the archaeological zone context near the Río Copalita.', verdict='Best for: archaeology context, river-mouth scenery, Bocana beach, surf-watch afternoons, and travelers who want something beyond resort bays. Avoid if you need predictable swimming; water and surf conditions can be stronger here.', plan='Check the INAH status of Bocana del Río Copalita first, then choose whether the day is about the archaeological zone, Bocana beach restaurants, or a scenic west-coast drive. Keep transport arranged because taxis can be less casual than in La Crucecita or Santa Cruz.', pair='Pair with Tangolunda if you are staying east, Chahué if you want a softer beach before or after, or Mazunte/Puerto Ángel only if you are ready for a longer coastal day.'),
'/towns-cities/mazunte/': dict(title='Mazunte Day Trip Guide | Top Huatulco', h1='Mazunte', intro='Mazunte is not Huatulco; it is a slower Oaxaca coast village that works as a day trip or overnight add-on when you want turtle-center context, Punta Cometa sunsets, and a different beach-town rhythm.', verdict='Best for: day-trippers with an early start, turtle/conservation interest, Punta Cometa, San Agustinillo pairing, and travelers considering an overnight coast extension. Avoid as a rushed late-afternoon add-on from Huatulco.', plan='Leave early, pick one anchor such as the Mexican Turtle Center area or Punta Cometa, and keep the day simple. Roads and coastal stops make the trip feel longer than a map glance suggests, so do not stack Mazunte, Zipolite, Puerto Ángel, and multiple beaches unless you have a driver and a long day.', pair='Pair with San Agustinillo for a gentler beach stop, Zipolite only if its open-coast identity genuinely fits your group, or Puerto Ángel for a fishing-port contrast on the way back.'),
'/towns-cities/puerto-angel/': dict(title='Puerto Ángel Day Trip Guide | Top Huatulco', h1='Puerto Ángel', intro='Puerto Ángel is a working coastal town and fishing port west of Huatulco, useful for visitors who want a less resort-like view of the Oaxaca coast.', verdict='Best for: a coastal drive, fishing-port atmosphere, simple seafood, and a contrast with manicured Huatulco bays. Avoid if you are looking for a polished beach-club day or guaranteed easy swimming.', plan='Treat Puerto Ángel as one stop in a western-coast day, not a replacement for Huatulco. Build the route around daylight, return transport, and whether you also want Zipolite, San Agustinillo, or Mazunte. Keep expectations honest: the draw is local texture, not resort comfort.', pair='Pair with Mazunte if you can leave early, with San Agustinillo for a softer beach break, or with Bocana/Copalita if you want a shorter west-side outing.'),
}

for route, d in TOWN_DATA.items():
    body = f"""
<section class='section-pad'><div class='container-xl max-w-5xl'>
  <div class='grid gap-6 lg:grid-cols-[1.1fr_.9fr]'>
    <div class='card p-7'><p class='text-sm font-bold uppercase tracking-[.16em] text-primary'>Quick verdict</p><h2 class='mt-2'>How to use {d['h1']}</h2><p class='mt-3 leading-7 text-ink/75'>{d['verdict']}</p></div>
    <div class='card bg-surface p-7'><p class='text-sm font-bold uppercase tracking-[.16em] text-primary'>Best fit</p><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'><li>Choose it when the page purpose matches your day, not because it is another dot on the map.</li><li>Build transport before dinner or sunset; return taxis are easier from town centers than remote beaches.</li><li>Keep cash and offline maps handy once you leave the main Huatulco bay loop.</li></ul></div>
  </div>
  <div class='mt-8 grid gap-6 md:grid-cols-3' data-town-decision-grid='true'>{card('How to plan it', d['plan'])}{card('Pair it with', d['pair'])}{card('Common mistake', 'Trying to visit every town in one day. The Oaxaca coast rewards fewer stops, earlier starts, and enough time for meals, heat, road curves, and a relaxed return.')}</div>
</div></section>
<section class='section-pad bg-white'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>Mini route for a first visit</h2><div class='mt-5 grid gap-4 md:grid-cols-3'><div class='rounded-3xl bg-secondary p-5'><strong>Start</strong><p class='mt-2 text-sm leading-6 text-ink/75'>Arrive with one clear anchor: meal, market, boat departure, archaeology, turtle-center context, or sunset.</p></div><div class='rounded-3xl bg-secondary p-5'><strong>Middle</strong><p class='mt-2 text-sm leading-6 text-ink/75'>Add one nearby stop that makes geographic sense instead of zig-zagging across the coast.</p></div><div class='rounded-3xl bg-secondary p-5'><strong>Finish</strong><p class='mt-2 text-sm leading-6 text-ink/75'>Return before the group is tired; save the second town or beach for another morning.</p></div></div></div></div></section>
{source_box([('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'destination context for the nine bays and Huatulco area'), ('Visit Mexico: Huatulco', 'https://visitmexico.com/en/destino/2183/huatulco-oaxaca', 'broad destination context'), ('Bocana del Río Copalita - INAH', 'https://www.inah.gob.mx/zonas/zona-arqueologica-bocana-del-rio-copalita', 'official archaeology context when using Copalita')])}
"""
    write(route, page(d['title'], d['intro'], route, 'Town guide', d['h1'], d['intro'], body))

# Towns hub
hub_cards=''.join(card(name, text) for name,text in [
('La Crucecita', 'Your practical center for dinner, errands, markets, banks, cafés, and a first-night town walk. Best paired with Chahué or Santa Cruz.'),
('Santa Cruz', 'Use it for boat-tour departures, waterfront meals, easy swimming, cruise-day services, and a simple marina-facing half day.'),
('Copalita / Bocana', 'The west-side context stop: river mouth, Bocana beach, surf energy, and INAH archaeology status to verify before going.'),
('Mazunte', 'A longer west-coast day or overnight add-on for turtle-center context, Punta Cometa, San Agustinillo, and slower beach-town rhythm.'),
('Puerto Ángel', 'A working fishing-port contrast to the resort bays. Better as one stop on a coastal route than as a polished beach-club day.'),
])
write('/towns-cities/', page('Huatulco Towns and Nearby Places | Top Huatulco', 'Choose between La Crucecita, Santa Cruz, Copalita, Mazunte, and Puerto Ángel with practical route logic.', '/towns-cities/', 'Towns and nearby places', 'Huatulco Towns and Nearby Places', 'Huatulco is not one town. Use this guide to choose the right town, bay base, or west-coast side trip for the day you actually want.', f"""
<section class='section-pad'><div class='container-xl max-w-6xl'><div class='card p-7'><h2>Choose by purpose, not by list-counting</h2><p class='mt-3 leading-7 text-ink/75'>La Crucecita solves food and errands. Santa Cruz solves boat logistics. Copalita adds river-mouth and archaeology context. Mazunte and Puerto Ángel are longer Oaxaca coast outings, not casual filler between beach stops.</p></div><div class='mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3' data-town-decision-grid='true'>{hub_cards}</div></div></section>
<section class='section-pad bg-surface'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>Simple route logic</h2><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'><li><strong>Short evening:</strong> La Crucecita dinner, zócalo, mezcal or coffee, then taxi back.</li><li><strong>Boat day:</strong> Santa Cruz start, bay route, late lunch, then La Crucecita if you still have energy.</li><li><strong>West-side culture:</strong> Copalita/Bocana first, then choose either Chahué/Tangolunda return or a longer Mazunte direction.</li><li><strong>Full coast day:</strong> Mazunte, San Agustinillo, and possibly Puerto Ángel with an early start and planned return.</li></ul></div></div></section>
{source_box([('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'destination and bay context'), ('Visit Mexico: Huatulco', 'https://visitmexico.com/en/destino/2183/huatulco-oaxaca', 'official destination overview'), ('INAH Copalita', 'https://www.inah.gob.mx/zonas/zona-arqueologica-bocana-del-rio-copalita', 'archaeology reference for Copalita side trips')])}"""))

GUIDES = {
'/travel-guide/airport-arrival/': ('Huatulco Airport Arrival Guide | Top Huatulco','Airport arrival','Huatulco Airport Arrival Guide','HUX is compact, but your first hour still matters: choose official taxi, private transfer, rental car, or hotel pickup before you walk outside.', ['Use the authorized airport taxi/transport desk if you have not prebooked.', 'Prebook private transfer for late arrivals, large families, surf luggage, or west-coast towns.', 'Rent a car only if you will use it beyond resort-to-town taxi hops.', 'Have your hotel zone ready: Tangolunda, Chahué, Santa Cruz, La Crucecita, Conejos, or west coast.'], 'Best move: arrange the first transfer before arrival, then solve local taxis once you understand your base. Do not land tired and start negotiating a multi-stop route.'),
'/travel-guide/getting-around/': ('Getting Around Huatulco | Top Huatulco','Transport guide','Getting Around Huatulco','Huatulco is compact around the main bays, but remote beaches and west-coast towns need more planning than a simple taxi hop.', ['Taxis are easiest for La Crucecita, Santa Cruz, Chahué, Tangolunda, and dinner returns.', 'Boat days usually start at Santa Cruz or a hotel/marina channel; confirm meeting point, pickup, and return.', 'Remote bays such as Cacaluta, Chachacual, Órgano, and Conejos require conditions-aware planning.', 'Rental cars help for Mazunte, Puerto Ángel, Copalita, and independent beach days, but parking/roads/insurance still matter.'], 'Best move: match transport to the day. Taxi for town/bay loops, boat for bay-hopping, driver or rental for west-coast day trips.'),
'/travel-guide/best-time-to-visit/': ('Best Time to Visit Huatulco | Top Huatulco','Season guide','Best Time to Visit Huatulco','The best month depends on whether you care more about dry weather, calmer boat mornings, lower crowds, greenery, or comfortable evenings.', ['Dry-season months are easier for first-timers who want predictable beach days.', 'Green-season travel can be beautiful, but plan earlier starts and flexible afternoons.', 'Holiday periods bring higher demand; book lodging, boats, and dinner anchors earlier.', 'Sea conditions matter more than month labels for snorkeling and remote bay days.'], 'Best move: protect your first calm morning for snorkeling or a boat route, then keep a town/market/Copalita fallback for wind, swell, or rain.'),
'/travel-guide/safety/': ('Huatulco Safety Guide | Top Huatulco','Safety guide','Huatulco Safety Guide','Safety in Huatulco is mostly about water, heat, transport, remote beaches, cash habits, and not treating every bay as equally easy.', ['Respect flags, swell, boat-captain judgment, and local advice; protected bay does not mean every water day is safe.', 'Use planned transport for late returns, remote bays, or west-coast towns.', 'Carry water, sun protection, and cash, especially away from La Crucecita and resort areas.', 'Do not leave valuables visible in cars or unattended on quiet beaches.'], 'Best move: pick beaches by conditions and group ability, not just photos. Remote beaches are rewarding only when access, water, and return logistics are under control.'),
'/travel-guide/first-time-visitors/': ('First Time in Huatulco | Top Huatulco','First-timer guide','First Time in Huatulco','A first Huatulco trip works best when you understand the bay system, choose a base, and avoid trying to see the entire coast in two days.', ['Choose your base first: Tangolunda/resort comfort, Chahué balance, Santa Cruz boat logistics, or La Crucecita food/errands.', 'Use one boat day, one town/market evening, one easy beach day, and one west-side or archaeology option.', 'Do not compare Huatulco to one continuous beach strip; it is a set of bays with different access and services.', 'Keep one flexible day for sea conditions, rest, or a favorite beach repeat.'], 'Best move: plan around three anchors: where you sleep, your calmest-water morning, and your best dinner/town night.'),
'/travel-guide/money-tipping/': ('Money, Tipping, and Payments in Huatulco | Top Huatulco','Money guide','Money, Tipping & Payments','Huatulco is easy with cards in hotels and many restaurants, but cash still matters for taxis, markets, tips, small beaches, and flexible day trips.', ['Use bank ATMs in town or hotel zones when possible and avoid relying on one machine.', 'Carry small bills for taxis, market food, bathroom/change needs, beach palapas, and tips.', 'Ask before assuming card acceptance at small restaurants, boats, and remote stops.', 'Keep volatile prices out of your mental plan; verify current rates locally.'], 'Best move: start each beach or town day with small cash, then use cards for larger restaurant/hotel charges where accepted.'),
'/travel-guide/packing-list/': ('Huatulco Packing List | Top Huatulco','Packing guide','Huatulco Packing List','Pack for strong sun, boat spray, uneven town walking, cash-based beach stops, and the difference between resort days and remote bay days.', ['Reef-conscious sun protection, hat, sunglasses, rash guard, and water bottle matter more than extra outfits.', 'Bring sandals for beach days and real walking shoes for Copalita, town wandering, or rocky access.', 'Dry bag or waterproof pouch helps on boat tours and snorkeling mornings.', 'Small first-aid, motion-sickness support, insect repellent, and copies of key documents are practical, not overkill.'], 'Best move: pack one small day kit that works for boat, beach, and town. Huatulco days often combine all three.'),
}
for route, (title,kicker,h1,intro, bullets, verdict) in GUIDES.items():
    bullet_html=''.join(f"<li>{b}</li>" for b in bullets)
    body=f"""<section class='section-pad'><div class='container-xl max-w-5xl'><div class='grid gap-6 lg:grid-cols-[1fr_.9fr]'><div class='card p-7'><p class='text-sm font-bold uppercase tracking-[.16em] text-primary'>Quick verdict</p><h2 class='mt-2'>What to do first</h2><p class='mt-3 leading-7 text-ink/75'>{verdict}</p></div><div class='card bg-surface p-7'><h2>Practical rules</h2><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'>{bullet_html}</ul></div></div><div class='mt-8 grid gap-6 md:grid-cols-3'>{card('Choose this approach if', 'You want a low-stress trip where transport, money, weather, and safety decisions are handled before they become problems.')}{card('Avoid this mistake', 'Do not plan Huatulco as if every bay, town, and attraction has the same access, services, and return options.')}{card('Pair with these guides', "Use the <a class='font-bold text-primary' href='/destinations/'>bay guide</a>, <a class='font-bold text-primary' href='/towns-cities/'>towns guide</a>, and <a class='font-bold text-primary' href='/itineraries/'>itineraries</a> together.")}</div></div></section>{source_box([('Huatulco Airport', 'https://www.huatulco-airport.com/', 'flight and airport-transfer context'), ('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'destination overview and bay context'), ('Visit Mexico: Huatulco', 'https://visitmexico.com/en/destino/2183/huatulco-oaxaca', 'official tourism overview')])}"""
    write(route, page(title, intro, route, kicker, h1, intro, body))

# travel guide hub
hub=''.join(card(t, d) for t,d in [('Airport arrival','Pick official taxi, transfer, rental car, or hotel pickup before you land.'),('Getting around','Know when taxis are enough and when remote beaches or west-coast towns need a driver/rental.'),('Best time','Plan around dry season, green season, holidays, and sea conditions.'),('Safety','Focus on water, heat, transport, cash, and remote-beach common sense.'),('Money & tipping','Use cards where easy, but carry small cash for taxis, markets, beaches, and tips.'),('Packing','Pack for sun, boats, town walking, and mixed beach/market days.')])
write('/travel-guide/', page('Huatulco Travel Guide | Top Huatulco','Practical Huatulco travel guide covering airport arrival, transport, seasons, safety, money, and packing.', '/travel-guide/', 'Practical travel guide', 'Huatulco Travel Guide', 'Use this section to solve the practical parts of the trip before you choose every beach: arrival, transport, seasons, safety, cash, and what to pack.', f"<section class='section-pad'><div class='container-xl max-w-6xl'><div class='card p-7'><h2>Start with logistics, then pick beaches</h2><p class='mt-3 leading-7 text-ink/75'>Huatulco is easy when you keep the map honest. The main bays and La Crucecita are compact; remote bays, archaeology, Mazunte, and Puerto Ángel need earlier starts and clearer transport.</p></div><div class='mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3'>{hub}</div></div></section>{source_box([('Huatulco Airport', 'https://www.huatulco-airport.com/', 'airport and transfer context'), ('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'destination context')])}"))

# itineraries
ITINS={
'/itineraries/4-days-relax-snorkel/': ('4 Days Relax + Snorkel | Top Huatulco','4 Days Relax + Snorkel','Slower pacing for couples or families who want beach time, a real snorkel morning, one town evening, and enough backup room for wind or tired kids.', ['Settle into Tangolunda, Chahué, or Santa Cruz; swim at the home bay; early La Crucecita dinner.', 'Use the calmest morning for a snorkel/boat plan: Maguey, La Entrega, San Agustín, Chachacual, or Cacaluta depending on conditions and operator route.', 'Market and culture day: La Crucecita, Mercado 3 de Mayo, church/zócalo, then Chahué sunset or easy seafood.', 'Choose the missing piece: San Agustín for beach lunch, Copalita/Bocana for context, or a resort/rest day if the group needs it.']),
'/itineraries/snorkel-boat-day/': ('Snorkel + Boat Day Plan | Top Huatulco','Snorkel + Boat Day Plan','A one-day plan for visitors who want a bay boat route without pretending every snorkel stop is equally calm, easy, or right for every group.', ['Start early at Santa Cruz or your confirmed pickup; verify route, inclusions, shade, reef rules, and return time.', 'Prioritize one or two realistic snorkel stops rather than racing through every bay. Maguey/La Entrega are easier; Chachacual/Cacaluta depend more on route and sea.', 'Use lunch as part of the day, not an afterthought: Maguey or San Agustín-style beach lunch works better than returning hungry and rushed.', 'Finish with a low-effort evening: La Crucecita dinner, Chahué sunset, or hotel rest. Do not stack a long west-coast drive after a boat day.'])
}
for route,(title,h1,intro,days) in ITINS.items():
    cards=''.join(f"<div class='card p-6' data-itinerary-day='{i}'><div class='text-sm font-bold uppercase tracking-[.16em] text-primary'>Day {i}</div><p class='mt-3 leading-7 text-ink/75'>{txt}</p></div>" for i,txt in enumerate(days,1))
    body=f"<section class='section-pad'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>Base and pacing strategy</h2><p class='mt-3 leading-7 text-ink/75'>Choose Tangolunda for resort ease, Chahué for balance, Santa Cruz for boat logistics, or La Crucecita if meals and errands matter most. Protect mornings for water and use afternoons for town, rest, or a flexible backup.</p></div><div class='mt-8 grid gap-6'>{cards}</div><div class='mt-8 grid gap-6 md:grid-cols-3'>{card('Choose', 'Use this plan if you want calm pacing and enough structure to avoid wasting the best water mornings.')}{card('Avoid', 'Do not use it if your goal is to tick every bay, every town, and Mazunte in the same short trip.')}{card('Backup', 'If wind or rain changes the water plan, swap in La Crucecita, Copalita/Bocana, or a protected home-bay day.')}</div></div></section>{source_box([('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'bay and destination context'), ('Huatulco Airport', 'https://www.huatulco-airport.com/', 'arrival/transport context')])}"
    write(route, page(title, intro, route, 'Huatulco itinerary', h1, intro, body))

itinhub=''.join(card(t,d) for t,d in [('3 days','Arrival, central bay, boat day, and La Crucecita/Copalita choice.'),('4 days relax + snorkel','Better for families/couples who want real beach time, not a checklist.'),('5 days Oaxaca coast','Adds west-coast context such as Mazunte or Puerto Ángel without rushing every day.'),('Snorkel + boat day','A single-day route that keeps lunch, conditions, and return energy realistic.')])
write('/itineraries/', page('Huatulco Itineraries | Top Huatulco','Choose a Huatulco itinerary by pace, base area, boat day, west-coast ambition, and weather backup.', '/itineraries/', 'Trip plans', 'Huatulco Itineraries', 'Pick an itinerary by energy level, not just trip length. The best Huatulco plan protects calm mornings, avoids zig-zag routes, and leaves room for sea conditions.', f"<section class='section-pad'><div class='container-xl max-w-6xl'><div class='card p-7'><h2>How to choose your plan</h2><p class='mt-3 leading-7 text-ink/75'>First-timers usually need one boat/snorkel morning, one town/market evening, one easy beach day, and one flexible slot. Longer trips can add Copalita, Mazunte, Puerto Ángel, or a second bay without turning the vacation into transport work.</p></div><div class='mt-8 grid gap-6 md:grid-cols-2'>{itinhub}</div></div></section>{source_box([('Visita Huatulco', 'https://en.visitahuatulco.mx/', 'bay context for itinerary routing'), ('Visit Mexico: Huatulco', 'https://visitmexico.com/en/destino/2183/huatulco-oaxaca', 'destination overview')])}"))

# food culture rewrite preserving required media/markers names
food_body=f"""
<section class='bg-background pb-2' data-approved-route-media='true' data-media-pass='second'><div class='container-xl'><figure class='overflow-hidden rounded-[2rem] border border-white bg-white shadow-card'><img src='/images/photos/huatulco-la-crucecita-oaxaca-mexico-jpg-food-culture.webp' alt='La Crucecita town center context for Huatulco food and culture planning' class='h-72 w-full object-cover sm:h-96' loading='eager' decoding='async' width='1600' height='1200'><figcaption class='px-5 py-3 text-xs font-semibold text-ink/60'>Reviewed image: La Crucecita Oaxaca Mexico. Approved town image used for the food/culture hub because most named restaurants and markets cluster in La Crucecita. Full credit on the Sources & credits page.</figcaption></figure></div></section>
<section class='section-pad' data-entity-depth='food-culture'><div class='container-xl max-w-6xl'>
  <div class='grid gap-6 lg:grid-cols-[1fr_.9fr]'>
    <div class='card p-7'><p class='text-sm font-bold uppercase tracking-[.16em] text-primary'>Quick verdict</p><h2>Use La Crucecita for planned meals; use the bays for seafood lunches.</h2><p class='mt-3 leading-7 text-ink/75'>Huatulco food works best as a two-part plan: town for Oaxacan restaurants, coffee, mezcal, markets, and reliable dinner choices; bays for simple seafood lunches after swimming or boat days.</p></div>
    <div class='card bg-surface p-7'><h2>Choose / avoid</h2><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'><li><strong>Choose La Crucecita</strong> for Terra-Cotta, El Sabor de Oaxaca, Mercado 3 de Mayo, coffee, mole, tlayudas, chocolate, mezcal, and evening variety.</li><li><strong>Choose Santa Cruz, Maguey, or similar beach palapa stops</strong> for grilled fish, shrimp, ceviche-style lunches, and easy meals tied to boat or beach plans.</li><li><strong>Avoid</strong> treating online rankings as fixed truth; menus, ownership, staffing, and hours change, so verify details the same week.</li></ul></div>
  </div>
  <div class='mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3' data-food-directory='true'>
    {card('Terra-Cotta', 'Best first-night reliable pick: a long-running La Crucecita anchor for breakfast, mole, Oaxacan cooking, coffee from Pluma Hidalgo, and a calm dinner when you want a known town option.')}
    {card('El Sabor de Oaxaca', 'Best for regional dishes in town: use it when you want Oaxacan flavors instead of another beachfront seafood meal. Check current hours and ask about dinner reservations before going.')}
    {card('Mercado 3 de Mayo', 'Best daytime food stop: browse produce, simple fonda-style meals, chocolate, coffee, mezcal, and everyday town life before a beach or rest afternoon.')}
    {card('Casa Bocana', 'Best paired with Bocana/Copalita: consider it for a meal, drink, or sunset-leaning plan on the west side. Confirm current service and return transport before building the day around it.')}
    {card('Mercader', 'Best contemporary town option to verify: consider Mercader when you want a more polished dinner or drink stop after several traditional Oaxacan meals. Confirm location, hours, and reservation needs before going.')}
    {card('Bay seafood palapas', 'Best beach-day lunch: order simply, ask about the catch or grilled seafood options, and keep enough cash for palapas that may not handle cards reliably.')}
  </div>
</div></section>
<section class='section-pad bg-white'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>A better food plan for 3 to 5 days</h2><div class='mt-5 grid gap-4 md:grid-cols-3'><div class='rounded-3xl bg-secondary p-5'><strong>Night 1</strong><p class='mt-2 text-sm leading-6 text-ink/75'>La Crucecita dinner so you learn the town grid, ATMs, pharmacies, and taxi rhythm.</p></div><div class='rounded-3xl bg-secondary p-5'><strong>Boat or beach day</strong><p class='mt-2 text-sm leading-6 text-ink/75'>Seafood lunch at the bay you are actually visiting; do not cross town just because a list says so.</p></div><div class='rounded-3xl bg-secondary p-5'><strong>Market morning</strong><p class='mt-2 text-sm leading-6 text-ink/75'>Mercado 3 de Mayo, coffee, chocolate, mezcal browsing, then a flexible beach or rest afternoon.</p></div></div></div></div></section>
<section class='section-pad bg-surface' data-visible-sources='true'><div class='container-xl max-w-5xl'><div class='card p-7'><h2>Current details to verify</h2><ul class='mt-4 list-disc space-y-3 pl-5 leading-7 text-ink/75'><li><a class='font-bold text-primary hover:underline' href='https://www.terracotta.com.mx/es/'>Terra-Cotta official site</a> — menu, location, and reservation context.</li><li><a class='font-bold text-primary hover:underline' href='https://en.visitahuatulco.mx/'>Visita Huatulco</a> — destination and bay context.</li><li>Restaurant social pages or direct calls — same-week hours, closing days, holiday reservations, and payment options.</li></ul></div></div></section>
"""
write('/food-culture/', page('Food and Culture in Huatulco | Top Huatulco', 'Visitor-first Huatulco food guide with La Crucecita restaurants, market stops, bay seafood logic, and what to verify before choosing dinner.', '/food-culture/', 'Food and culture', 'Food and Culture in Huatulco', 'Use this guide to decide where food fits into the trip: town dinners, market mornings, bay seafood lunches, and the Oaxacan dishes worth planning around.', food_body, "<meta name='x-approved-media' content=\"data-approved-route-media='true' La Crucecita Oaxaca Mexico\">"))

# source map append
src = ROOT/'CONTENT_ENRICHMENT_SOURCES.md'
append = """

## Visitor-reference depth pass — towns, itineraries, travel guide, food (2026-05-30)

Purpose: respond to launch-blocking thin content in towns, itineraries, travel-guide, and food sections. Copy rules: visitor-facing decisions first; no hard-coded volatile prices/hours; visible source/live-check links where the visitor needs current details.

Sources and usage notes:
- https://en.visitahuatulco.mx/ — broad Huatulco/nine-bay destination context used for town, itinerary, and travel-guide route logic.
- https://visitmexico.com/en/destino/2183/huatulco-oaxaca — official destination overview used for positioning and durable context.
- https://www.huatulco-airport.com/ — airport/arrival/transport context; pages still tell visitors to verify current operators and transfer details.
- https://www.inah.gob.mx/zonas/zona-arqueologica-bocana-del-rio-copalita — official Copalita archaeology context used for Copalita town/travel routing.
- https://lugares.inah.gob.mx/es/node/4487 — INAH place record cross-check for Bocana del Río Copalita.
- https://www.terracotta.com.mx/es/ — restaurant-specific source for Terra-Cotta references on food/La Crucecita pages.
- Restaurant/operator social or official pages should be checked same-week before relying on hours, reservations, menus, or holiday service.
"""
text = src.read_text(encoding='utf-8') if src.exists() else '# Content enrichment sources\n'
if 'Visitor-reference depth pass — towns, itineraries, travel guide, food' not in text:
    src.write_text(text.rstrip()+append+'\n', encoding='utf-8')

print('visitor reference depth pass applied')
